<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="CRM App Test Automation" duration-ms="62753" started-at="2019-06-20T13:03:48Z" finished-at="2019-06-20T13:04:51Z">
    <groups>
    </groups>
    <test name="CRM APP Test" duration-ms="62753" started-at="2019-06-20T13:03:48Z" finished-at="2019-06-20T13:04:51Z">
      <class name="com.crm.testcases.HomePageTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.crm.testcases.HomePageTest@5b275dab]" name="SetUp" is-config="true" duration-ms="17684" started-at="2019-06-20T18:34:30Z" finished-at="2019-06-20T18:34:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="ValidateCRMHomepage()[pri:0, instance:com.crm.testcases.HomePageTest@5b275dab]" name="ValidateCRMHomepage" duration-ms="1717" started-at="2019-06-20T18:34:48Z" finished-at="2019-06-20T18:34:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCRMHomepage -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.crm.testcases.HomePageTest@5b275dab]" name="quit" is-config="true" duration-ms="815" started-at="2019-06-20T18:34:50Z" finished-at="2019-06-20T18:34:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.crm.testcases.HomePageTest -->
      <class name="com.crm.testcases.LoginTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="SetUp" is-config="true" duration-ms="19233" started-at="2019-06-20T18:33:48Z" finished-at="2019-06-20T18:34:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="ValidateTitle()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="ValidateTitle" duration-ms="503" started-at="2019-06-20T18:34:07Z" finished-at="2019-06-20T18:34:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [#1 Free CRM software in the Cloud FreeCRM] but found [Free CRM software for any Business]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [#1 Free CRM software in the Cloud FreeCRM] but found [Free CRM software for any Business]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.crm.testcases.LoginTest.ValidateTitle(LoginTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="quit" is-config="true" duration-ms="820" started-at="2019-06-20T18:34:08Z" finished-at="2019-06-20T18:34:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="SetUp" is-config="true" duration-ms="8411" started-at="2019-06-20T18:34:09Z" finished-at="2019-06-20T18:34:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="validatelogin()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="validatelogin" duration-ms="12699" started-at="2019-06-20T18:34:17Z" finished-at="2019-06-20T18:34:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatelogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.crm.testcases.LoginTest@cb5822]" name="quit" is-config="true" duration-ms="826" started-at="2019-06-20T18:34:30Z" finished-at="2019-06-20T18:34:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.crm.testcases.LoginTest -->
    </test> <!-- CRM APP Test -->
  </suite> <!-- CRM App Test Automation -->
</testng-results>
